### PR TITLE
A few changes

### PR DESCRIPTION
**Pull request by IsmaelMartinez**
Hi @JamieMagee ,

I can't find a way to communicate with you other than creating a pull request. 

I have made a few changes to the repo but reverted most of the move to TS as it wasn't helping me during development (debug, etc).

Are you maintaining this project? It looks as dead as the one from @ivelkov.

If you are actively maintaining it, let me know so we can discuss the best way to merge my changes in.

Thanks!
Ismael

### CODE REVIEW

**Comment by JamieMagee** [comment]
Hey,

Thanks for getting in touch. It's probably easiest to catch me on here, or on Twitter.

I just checked in `master` branch and I had source maps disabled. That would definitely make debugging difficult.

I am trying to maintain the project, and have spent most of the free time I've had working on a rewrite to make the code easier to work on. Check out the `rewrite` branch to see what I've got. Unfortunately I hit a bit of a brick wall, and I'm not an electron expert. Maybe you have a better insight into what I'm doing wrong? See #3 for a screenshot.

**Comment by IsmaelMartinez** [comment]
Hi @JamieMagee ,

I am neither an electron expert but I will have a look.

It might be one of the webPreferences. 

I haven't done any typescript but happy to learn about.

by the way... why don't you activate the "issues" or create a "project" in here so people can easily contribute/help ?

I will get back to you on that issue if I find anything on it.

**Comment by IsmaelMartinez** [comment]
by the way, don't even try to merge this... I did revert to before you move to TS so it will be fairly difficult to get it all working. This was just to be able to communicate with you.

**Comment by JamieMagee** [comment]
Yeah, I'm also looking at it this evening.

I would thoroughly recommend Typescript. I find a lot of potential bugs a lot earlier in development with it.

I've enabled issues

**Comment by IsmaelMartinez** [comment]
Perfect. Just remove this pull request (or leave it for reference). I can only work a few hours here and there and then 3/4 hours on Friday after lunch, but most of the hacks are done in this fork. It will be nice to structure it properly so people can contribute.

**Pull request closed without merging**
