### PR TITLE
Add CSS to hide download desktop/mobile app buttons

### PR DESCRIPTION
**Pull request by jhult**
Since we are using Electron to display the web view, Teams thinks we may want to download the desktop or mobile apps. This PR includes CSS to hide these buttons.

### CODE REVIEW

**Comment by maximbaz** [comment]
Cool idea, what we should also hide is this annoying popup, which appears when you paste some text with <kbd>Ctrl+Shift+V</kbd> to remove formatting:

image

The selector for the entire notification is `.cke_notifications_area`. 

Can do in a separate PR if you don't want to pollute this one 😉

**Comment by jhult** [comment]
Ultimately, it would be nice to store CSS in a separate file and load it in. If people agree, I can take a swipe at doing it.

I think the way to do it is outlined [here](https://discuss.atom.io/t/inject-css-to-loadurl/26845/6).

**Comment by JamieMagee** [comment]
Great idea! I'm just going to hold off on this temporarily as I'm working on a more readable re-write (based off eNkru/electron-outlook). I'll push a branch with what I've got so far, tomorrow.

**Comment by jhult** [comment]
@JamieMagee, any luck with this?

**Comment by JamieMagee** [comment]
@jhult Hey, I'm still here :) I had hit a bit of a brick wall with the rewrite. Something to do with ipc being null. Maybe you have some insight?

image

**Comment by IsmaelMartinez** [comment]
Hi, got it 

you need to set the userAgent and probably best if you use the partition nopersist (at least during development). If you give me rights I send a pull request.

--edit
well, as it was such a small change, I have added in this path https://github.com/JamieMagee/teams-for-linux/compare/rewrite...IsmaelMartinez:patch-1

Thanks,

**Comment by JamieMagee** [comment]
@IsmaelMartinez Thank you! I've been struggling with this for over a week!

I'll push a commit shortly

**Comment by IsmaelMartinez** [comment]
I did suffer this during this week when I was playing with the userAgent to have mentions (they don't work if using the "edge" userAgent) , check the patch that I have created using the github UI, but probably best to give me access so I can push pull requests to that repo. 

Thanks!

**Comment by JamieMagee** [comment]
Actually, I'm not sure this is a complete fix. I have to login every time I open the app. It looks like `nopersist` fixes some things, but not everything.

**Comment by IsmaelMartinez** [comment]
well, is just to ensure the cache is clear specially if changing the userAgent. I have seen some strange stuff happening (like history disappearing when changing the userAgent).

Might be one of those things that needs to be configurable, but I do recommend using it at least for early development... or remember to try once with it if you start seen something strange.

**Comment by JamieMagee** [comment]
Okay, I have a complete fix. Setting `partition` to `nopersist` works correctly, but doesn't save your cookies between sessions. Not setting `partition` i.e. `null` doesn't work at all. Setting `partition` to `persist:teams` works as expected. I've just pushed the commit that fixes the issue. Thanks for all the help.

Sorry for hijacking this PR! I've merged your changes @jhult & @maximbaz in the `rewrite` branch. I think I'll tag a release (0.1.0) this weekend, and then work towards getting feature parity with the 0.0.x release afterwards.

**Comment by IsmaelMartinez** [comment]
Great, do let me know once i got access and I can start adding some of the changes from my branch so I don't need to support two projects.

**Pull request closed without merging**
